import { createClient } from "@/utils/supabase/server";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { z } from "zod";

// Input validation schema to ensure only valid email addresses are accepted
const inviteSchema = z.object({
	email: z.email("Invalid email format"),
});

/**
 * POST /api/invite
 *
 * This endpoint sends an invitation to a prospective user. Only authenticated
 * admins can call this route. It performs the following steps:
 *  1. Verify the caller is authenticated and has an admin role.
 *  2. Validate the request body to ensure a valid email is provided.
 *  3. Ensure the user does not already exist and no active invitation exists.
 *  4. Create an invitation record in the `invitations` table for auditing.
 *  5. Use the service role key to call Supabase's `inviteUserByEmail` with a
 *     redirect URL pointing to `/auth/signup`. The email template uses
 *     `{{ .ConfirmationURL }}` to construct the confirmation_url parameter.
 */
export async function POST(request: Request) {
	try {
		// 1. Get the user making the request
		const supabase = await createClient();
		const {
			data: { user },
			error: userError,
		} = await supabase.auth.getUser();

		if (userError || !user) {
			return NextResponse.json({ error: "Authentication required" }, { status: 401 });
		}

		// 2. Check if user is admin
		const { data: profile, error: profileError } = await supabase
			.from("profiles")
			.select("role")
			.eq("id", user.id)
			.single();

		if (profileError || profile?.role !== "admin") {
			return NextResponse.json({ error: "Admin privileges required" }, { status: 403 });
		}

		// 3. Validate request body
		const body = await request.json();
		const validationResult = inviteSchema.safeParse(body);

		if (!validationResult.success) {
			return NextResponse.json({ error: "Invalid email format" }, { status: 400 });
		}

		const { email } = validationResult.data;

		// 4. Check if user already exists
		const { data: existingUser } = await supabase.auth.admin.listUsers();
		const userExists = existingUser.users.some((u) => u.email === email);

		if (userExists) {
			return NextResponse.json({ error: "User already exists" }, { status: 400 });
		}

		// 5. Check if invitation already exists and is valid
		const { data: existingInvite } = await supabase
			.from("invitations")
			.select("*")
			.eq("email", email)
			.is("used_at", null)
			.gt("expires_at", new Date().toISOString())
			.single();

		if (existingInvite) {
			return NextResponse.json({ error: "Active invitation already exists for this email" }, { status: 400 });
		}

		// 6. Create invitation record. We still insert a row into the invitations
		// table to keep track of who invited whom and when. The token column
		// generated by the database will not be used in the auth flow.
		const { data: invitation, error: inviteError } = await supabase
			.from("invitations")
			.insert({
				email,
				invited_by: user.id,
			})
			.select()
			.single();

		if (inviteError) {
			console.error("Error creating invitation:", inviteError);
			return NextResponse.json({ error: "Failed to create invitation" }, { status: 500 });
		}

		// 7. Send invitation email using admin client. The admin client has
		// privileges to call `inviteUserByEmail`. We pass a redirectTo that
		// points to `/auth/signup`. When the user confirms the invitation the
		// confirmation_url provided in the email template will include the
		// `token_hash` and `type=invite` parameters. After verification Supabase
		// will redirect the user back to this path where we handle password setup.
		const supabaseAdmin = createAdminClient(
			process.env.NEXT_PUBLIC_SUPABASE_URL!,
			process.env.SUPABASE_SERVICE_ROLE_KEY!
		);

		const { origin } = new URL(request.url);
		const { error: emailError } = await supabaseAdmin.auth.admin.inviteUserByEmail(email, {
			redirectTo: `${origin}/auth/signup`,
			data: {
				invitation_id: invitation.id,
			},
		});

		if (emailError) {
			// Clean up invitation if email fails
			await supabase.from("invitations").delete().eq("id", invitation.id);
			console.error("Error sending invitation email:", emailError);
			return NextResponse.json({ error: "Failed to send invitation email" }, { status: 500 });
		}

		return NextResponse.json({
			message: "Invitation sent successfully",
			invitation: {
				id: invitation.id,
				email: invitation.email,
				expires_at: invitation.expires_at,
			},
		});
	} catch (error) {
		console.error("Unexpected error in invite API:", error);
		return NextResponse.json({ error: "Internal server error" }, { status: 500 });
	}
}
